name: "Prepare Shaders"
description: "Prepare shaders for validation or analysis (requires setup-build-environment to be called first)"

inputs:
    cmake-preset:
        description: "The CMake configure/build preset to use."
        required: false
        default: "ALL"

runs:
    using: "composite"
    steps:
        - name: Prepare shaders
          uses: lukka/run-cmake@v10
          with:
              configurePreset: ${{ inputs.cmake-preset }}
              configurePresetAdditionalArgs: "['-DBUILD_SHADER_TESTS=OFF']"
              buildPreset: ${{ inputs.cmake-preset }}
              buildPresetAdditionalArgs: "['--target prepare_shaders']"

        - name: Setup Python
          uses: actions/setup-python@v6
          with:
              python-version: "3.11"

        - name: Install hlslkit
          run: pip install git+https://github.com/alandtse/hlslkit.git
          shell: bash
